### ISSUE TITLE
Cards with different sizes

### ISSUE THREAD

**Issue by Tsettaro** [Tsettaro/anishop#3]
I think the problem CSS of mustard-ui file

**Comment by Tsettaro** [comment]
It's alright. The problem was in style.css:
``` CSS
.card {
  border: 1px solid #dedede;
  margin: auto;
  /* max-width: 100%;
  max-height: 90%; */
  height: 500px;
}
```
We need to comment max-width and max-height and make height is 500px
